openapi: 3.0.0
info:
  version: 1.0.0
  title: SCORE risk calculation v0.1.0
  description: SCORE risk calculation v0.1.0.
servers:
  - url: /score/calc/v0.1.0
tags:
  - name: KO Endpoints
paths:
  /score:
    post:
      tags:
        - KO Endpoints
      operationId: cvdriskscore
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
      x-kgrid-artifact:
        type: String
        value: score.js
      x-kgrid-adapterType:
        type: String
        value: JAVASCRIPT
      x-kgrid-entry:
        type: String
        value: score
components:
  schemas:
    input:
      required:
        - age
        - gender
        - risk
        - sbp
        - cholesterol
        - smoker
      properties:
        age:
          type: number
          x-kgrid-label: Patient Age
          x-kgrid-unit: yr
          example: 48
        gender:
          type: string
          x-kgrid-label: Gender of the patient
          x-kgrid-unit: ''
          enum:
            - Male
            - Female
          example: Female
        risk:
          type: string
          x-kgrid-label: Choose the population risk level
          x-kgrid-unit: ''
          enum:
            - high
            - low
          example: low
        sbp:
          type: number
          x-kgrid-label: Systolic Blood Pressure
          x-kgrid-unit: mmHg
          example: 120
        cholesterol:
          type: number
          x-kgrid-label: Total Cholesterol
          x-kgrid-unit: mmol/L
          example: 8
        smoker:
          type: boolean
          x-kgrid-label: Is the patient a current smoker?
          x-kgrid-unit: ''
          example: false
    output:
      type: object
      required:
        - result
      properties:
        result:
          type: object
          properties:
            cvdrisk:
              type: object
              properties:
                total:
                  type: number
                  x-kgrid-label: Total CVD Risk
                  example: 0.12
                chd:
                  type: number
                  x-kgrid-label: CHD Risk
                  example: 0.04
                nonchd:
                  type: number
                  x-kgrid-label: non-CHD Risk
                  example: 0.08
        info:
          type: object
