openapi: 3.0.0
info:
  version: 1.0.0
  title: New Hello World
  description: Hello World bundle.v2 with webpack-built payload
servers:
  - url: /hello/world/bundle.v2/
    description: Hello World bundle.v2 with webpack-built payload
tags:
  - name: KO Endpoints
    description: Hello World Endpoints
paths:
  /welcome:
    post:
      tags:
        - KO Endpoints
      description: Hello
      operationId: hello
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
      x-kgrid-activation:
        artifact: 'dist/main.js'
        adapter: 'JAVASCRIPT'
        entry: 'welcome'
      x-kgrid-artifact:
        type: String
        value: dist/main.js
      x-kgrid-adapterType:
        type: String
        value: JAVASCRIPT
      x-kgrid-entry:
        type: String
        value: welcome
components:
  schemas:
    input:
      required:
        - name
        - language
      properties:
        name:
          type: string
          x-kgrid-label: 'Please enter your name'
          x-kgrid-unit: ''
          example: Carol
        language:
          type: string
          enum: ['English','French', 'German','Italian','Portuguese','Spanish','Turkish' ]
          x-kgrid-label: 'Please select your language'
          x-kgrid-unit: ''
          example: Spanish
    output:
      required:
        - result
      properties:
        result:
          type: object
          additionalProperties:
            type: object
