openapi: 3.0.0
info:
  version: 1.0.0
  title: Example Executive Knowledge Object
  description: Example Executive Knowledge Object
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /exec/example/v1.0.0/
    description: Example Executive Knowledge Object
tags:
  - name: KO Endpoints
    description: Example Executive Knowledge Object v1.0.0
paths:
  /execute:
    post:
      tags:
        - KO Endpoints
      description: Executive Knowledge Object execute endpoint.
      operationId: executive
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/workrequest'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    workrequest:
      required:
        - name
        - iterations
        - steps
      properties:
        name:
          type: string
          example: Test 21
        iterations:
          type: integer
          example: 100000
        steps:
          type: integer
          example: 5
    workresponse:
      required:
        - result
      properties:
        result:
          type: object
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
